# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /jiujiu-admin

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000 # Maximum number of connections in the connection pool (use a negative value to indicate no limit)
        max-wait: -1ms # Maximum blocking waiting time of the connection pool (using a negative value means no limit)
        max-idle: 10 # The largest idle connection in the connection pool
        min-idle: 5 # The smallest idle connection in the connection pool
  freemarker:
    suffix: .html
    request-context-attribute: request

jiujiu:
  cluster: false  #Cluster configuration true cluster environment false stand-alone environment, you also need to open the spring-session-data-redis comment in pom.xml
  globalSessionTimeout: 3600   #Stand-alone environment, session expiration time is 60 minutes
  redis:
    open: false  #Whether to enable redis cache true open false close


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #Entity scan, multiple packages separated by commas or semicolons
  typeAliasesPackage: io.jiujiu.modules.*.entity
  global-config:
    #Database related configuration
    db-config:
      #Primary key type AUTO: "Database ID increment", INPUT: "User input ID", ID_WORKER: "Globally unique ID (numeric type unique ID)", UUID: "Globally unique ID UUID";
      id-type: AUTO
      #Field strategy IGNORED: "Ignore judgment", NOT_NULL: "Non-NULL judgment"), NOT_EMPTY: "Non-empty judgment"
      field-strategy: NOT_NULL
      #Hump underline conversion
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'